# Cat vs Dog Classification using CNN

This project demonstrates the classification of images into two categories: cats and dogs. It utilizes Convolutional Neural Networks (CNN) and is implemented in Python using the TensorFlow library. The data is loaded from image files and preprocessed to train the model for accurate classification.
Prerequisites

To run this project, you need to have the following libraries installed:

    TensorFlow
    pickle
    Sequential
    Dense
    Dropout
    Activation
    Flatten
    Conv2D
    MaxPooling2D

Dataset is first downloaded from the internet and saved in the computer    
Dataset link:https://www.microsoft.com/en-us/download/confirmation.aspx?id=54765
Dataset location:"C:/Datasets/petImages"

In [1]:
#before we start
#gray scale CNN try to make a color CNN
#c+rl + enter runs current shell
#pip -V

#pip install tensorflow
#pip install --upgrade tensorflow

#pip install opencv-python

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import os
#pip install opencv-python
import cv2

In [3]:
#RUN THIS BLOCK JUST TO SEE THE DOGS/CATS
DATADIR="C:/Datasets/petImages"
CATEGORIES = ["Dog", "Cat"]



In [4]:
#Tthis block can run independently
#making training data  

training_data=[]

#0 _> dot
#1 _> cat
DATADIR="C:/Datasets/petImages"
CATEGORIES = ["Dog", "Cat"]
#IMG_SIZE = 50
def create_training_data():
    for category in CATEGORIES:
        path = os.path.join(DATADIR, category)  #path to cats or dogs dir
        print(path)
        class_num = CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                #we use try because this process throws a bunch of errors
                #converting image to array
                img_array = cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE) #making all imgage grayscale, color not neeeded
                #new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                new_array = cv2.resize(img_array, (50, 50))
                training_data.append([new_array, class_num])
            except Exception as e:
                pass
            #plt.imshow(img_array, cmap="gray")
            #plt.show()
            #break
        #break
    

create_training_data()
print("hi")


C:/Datasets/petImages\Dog
C:/Datasets/petImages\Cat
hi


In [5]:
print(len(training_data))
print(type(training_data))

print(training_data[0][0])
print(training_data[0][0].shape)

print(training_data[0][1])

24946
<class 'list'>
[[115 160 159 ... 157 148 139]
 [121 164 166 ... 163 153 146]
 [124 161 164 ... 168 161 151]
 ...
 [155 128  88 ...  81  69  68]
 [ 87  95  72 ...  77  74  73]
 [ 75  78  79 ...  75  78  75]]
(50, 50)
0


In [6]:
# first part of training_data are only Dogs and then only cats

#we want to shuffle the data while feeding it to the model
import random
random.shuffle(training_data)


#for sample in training_data[:10]:
#    print(sample[1])

In [7]:
# x is feature and y is label

x = []
y = []


#new
#import numpy as np


#new


IMG_SIZE = 50

for features, label in training_data:
    x.append(features)
    y.append(label)

x = np.array(x).reshape(-1, IMG_SIZE,IMG_SIZE, 1) #-1 is how many feature, any number!. last 1 is because gayscale
#last will be 3 if this is a color instead of grayscale CNN.



In [8]:
#saving the data . we can use numpy save or pickle

import pickle
pickle_out = open("x.pickle", "wb")
pickle.dump(x, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()


#captial x small y lol
#lets fix that

#test 
#pickle_out = open("X.pickle", "wb")
pickle_out = open("x.pickle", "wb")
pickle.dump(x, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()

In [9]:
#lets see if we can open what we just have saved 
pickle_in = open("x.pickle","rb")
x = pickle.load(pickle_in)

x[1]

array([[[ 99],
        [ 86],
        [ 81],
        ...,
        [ 83],
        [ 95],
        [ 95]],

       [[ 77],
        [110],
        [ 83],
        ...,
        [ 91],
        [ 94],
        [106]],

       [[106],
        [ 83],
        [ 87],
        ...,
        [ 89],
        [106],
        [106]],

       ...,

       [[147],
        [149],
        [157],
        ...,
        [178],
        [175],
        [187]],

       [[156],
        [150],
        [153],
        ...,
        [184],
        [173],
        [175]],

       [[143],
        [155],
        [149],
        ...,
        [190],
        [179],
        [179]]], dtype=uint8)

# Now the classification part

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
import pickle 


In [11]:
#new
from tensorflow.keras.callbacks import TensorBoard
import time 


In [14]:


pickle_in = open("x.pickle","rb")
x = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)




#consider normalizing the data. this is done by scale the data
#so min 0 max 255px
#so to scale
x=x/255.0
#x=x/200.0


dense_layers=[0]
layer_sizes=[64,]
conv_layers=[3]

# dense_layers = [0, 1, 2]
# layer_sizes = [32, 64, 128]
# conv_layers = [1, 2, 3]

for dense_layer in dense_layers:
    for layer_size in layer_sizes:           #  
        for conv_layer in conv_layers:
            NAME = "{}-conv-{}-nodes-{}-dense-{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
            print(NAME)


            model = Sequential()

            #LAYER 1
            #conv layer = 64 unit, window = 3 by 3, input shape
            # (3,3) is the 3 by 3 window
            #model.add( Conv2D(64, (3,3), input_shape = x.shape[1:]) )
            model.add( Conv2D(layer_size, (3,3), input_shape = x.shape[1:]) )
            #after convotuional layer we are going to pass activation layer
            model.add(Activation("relu")) #actitation= rectifi linear
            #now we will do pooling
            model.add(MaxPooling2D(pool_size=(2,2)))
            
            for l in range(conv_layer -1):
                #

                #doing this again

                #Layer2
                #model.add(Conv2D(64, (3,3)))
                model.add(Conv2D(layer_size, (3,3)))
                model.add(Activation("relu"))
                model.add(MaxPooling2D(pool_size=(2,2)))
                
            model.add(Flatten())
            for l in range(dense_layer):
                #
                model.add(Dense(layer_size))
                model.add(Activation("relu"))
                





            #LAYER4 OUTPUT LAYER
            #now to make output layer
            model.add(Dense(1))
            model.add(Activation('sigmoid'))

            #y_pred? 
            #back propagation where? ANN, SGD, Momen
            model.compile(loss="binary_crossentropy", 
                          optimizer="adam", 
                          metrics=['accuracy'])



            #import numpy as np

            x = np.array(x)
            y = np.array(y)

            # Rest of your code...

            #model.fit(x, y, batch_size=32, validation_split=0.1)   #model.fit(x, y, batch_size=32, epochs=10,validation_split=0.3)
            model.fit(x, y, batch_size=32, epochs=10,validation_split=0.3)








# with  dense_layers=[0] layer_sizes=[64,] conv_layers=[3] validation split 0.3 we got val accuracy: 0.612
# and epochs = 10. we got 0.8159 accuracy
#maybe overfeeting happening



3-conv-64-nodes-0-dense-1690035033
Epoch 1/10
546/546 [==============================] - 31s 55ms/step - loss: 0.6492 - accuracy: 0.6187 - val_loss: 0.5988 - val_accuracy: 0.6824
Epoch 2/10
546/546 [==============================] - 32s 58ms/step - loss: 0.5626 - accuracy: 0.7133 - val_loss: 0.5663 - val_accuracy: 0.7082
Epoch 3/10
546/546 [==============================] - 30s 55ms/step - loss: 0.5022 - accuracy: 0.7587 - val_loss: 0.5182 - val_accuracy: 0.7413
Epoch 4/10
546/546 [==============================] - 29s 54ms/step - loss: 0.4617 - accuracy: 0.7819 - val_loss: 0.4760 - val_accuracy: 0.7668
Epoch 5/10
546/546 [==============================] - 29s 54ms/step - loss: 0.4320 - accuracy: 0.8029 - val_loss: 0.4758 - val_accuracy: 0.7690
Epoch 6/10
546/546 [==============================] - 30s 55ms/step - loss: 0.3940 - accuracy: 0.8212 - val_loss: 0.4468 - val_accuracy: 0.7866
Epoch 7/10
546/546 [==============================] - 29s 52ms/step - loss: 0.3606 - accuracy: 0.8391